# See https://docs.codecov.com/docs/codecovyml-reference#coverage
coverage:
  # The value range where you want the value to be green
  range: 70..100
  # Which direction to you want to round the coverage value (up, down, nearest)
  round: down
  # What precision do you want the coverage value to be
  precision: 2
  status:
    project:
      default:
        # See https://docs.codecov.com/docs/commit-status#informational: 
        #
        # Use Codecov in informational mode. Default is false. If true is
        # specified the resulting status will pass no matter what the coverage
        # is or what other settings are specified. Informational mode is great
        # to use if you want to expose codecov information to other developers
        # in your pull request without necessarily gating PRs on that
        # information. 
        informational: true
    patch:
      default:
        informational: true